<?php

/**
 * @file
 * Secure login module.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_form_alter().
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function securelogin_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  // Load secure login configuration.
  $conf = \Drupal::config('securelogin.settings');
  $other_forms = $conf->get('other_forms');
  // Changing the form id to the base form allows us to match all node forms
  // since the form id will be 'node_form'.
  if (isset($form_state->getBuildInfo()['base_form_id'])) {
    $form_id = $form_state->getBuildInfo()['base_form_id'];
  }
  if ($conf->get('all_forms')) {
    $form['#https'] = TRUE;
  }
  elseif ($conf->get('form_' . $form_id)) {
    $form['#https'] = TRUE;
  }
  elseif (!empty($other_forms) && is_string($other_forms) && in_array($form_id, explode(' ', $other_forms))) {
    $form['#https'] = TRUE;
  }
  elseif ($conf->get('form_webform_client_form') && isset($form['#webform_id']) && $form_id === "webform_submission_{$form['#webform_id']}_form") {
    $form['#https'] = TRUE;
  }
  if (!empty($form['#https'])) {
    \Drupal::service('securelogin.manager')->secureForm($form);
  }
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function securelogin_block_view_user_login_block_alter(array &$build, BlockPluginInterface $block): void {
  // User module alters the form action after the user login block is built, so
  // now we may need to re-secure it.
  $build['#pre_render'][] = 'securelogin.manager:userLoginBlockPreRender';
}

/**
 * Implements hook_help().
 */
function securelogin_help(?string $route_name, RouteMatchInterface $route_match): ?TranslatableMarkup {
  switch ($route_name) {
    case 'help.page.securelogin':
      return t('The Secure Login module allows user login and other forms to be submitted to a configurable secure (HTTPS) URL from the insecure (HTTP) site. By securing the user login forms, a site can enforce secure authenticated sessions, which are immune to <a rel="noreferrer" href="https://en.wikipedia.org/wiki/Session_hijacking">session hijacking</a>.');

    case 'securelogin.admin':
      return t('You may configure the user login and other forms to be submitted to the secure (HTTPS) base URL. By securing all forms that create a session, a site can enforce secure sessions which are immune to <a rel="noreferrer" href="https://en.wikipedia.org/wiki/Session_hijacking">session hijacking</a> by eavesdroppers.');
  }
  return NULL;
}

/**
 * Implements hook_securelogin_alter() for comment module.
 *
 * phpcs:disable Drupal.NamingConventions.ValidFunctionName.InvalidPrefix
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function comment_securelogin_alter(&$forms): void {
  $forms['comment_form']['#title'] = t('Comment form');
}

/**
 * Implements hook_securelogin_alter() for node module.
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function node_securelogin_alter(&$forms): void {
  $forms['node_form']['#title'] = t('Node form');
}

/**
 * Implements hook_securelogin_alter() for contact module.
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function contact_securelogin_alter(&$forms): void {
  $forms['contact_message_form']['#title'] = t('Contact form');
}

/**
 * Implements hook_securelogin_alter() for webform module.
 *
 * @phpstan-ignore-next-line Hook implementations should not duplicate @param
 *   documentation.
 */
function webform_securelogin_alter(&$forms): void {
  $forms['webform_client_form']['#title'] = t('Webform');
}
